#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "9fd2a226-c85f-4b28-8e3b-0dfb798a2408"

[vars]
R2_PUBLIC_URL = "https://pub-c88f2b9985144b68b07650ec7cf9703f.r2.dev"

[dev]
port = 5000
